# Dockerfile.node
FROM node:latest

WORKDIR /app

# Copy package.json and yarn.lock
COPY package.json ./

# Install dependencies
RUN yarn install

# Copy the rest of the application code
COPY . .

# Expose the ports for your application
EXPOSE 5173 3000 6006

# Default command to run your application (optional)
CMD ["yarn", "dev"]
