version: '3.8'

services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - '5173:5173' # Application develelopment
    command: yarn dev
  json-server:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - '3000:3000' # JSON server
    volumes:
      - ./data:/data # Assuming your JSON data is in a 'data' directory
    command: yarn server

  storybook:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - '6006:6006' # Storybook
    command: yarn storybook # Command to run Storybook

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - '80:80' # Expose Nginx on port 80
